### ISSUE TITLE
Documentation is broken

### ISSUE THREAD

**Issue by daredevildave** [namlook/mongokit#143]
There are no links to the Sphinx documentation available on http://namlook.github.io/mongokit

I can't seem to access the docs directly at all.

**Comment by wesinator** [comment]
https://namlook.github.io/mongokit/ is blank page in Firefox 
`Blocked loading mixed active content “http://documentup.com/namlook/mongokit?config=%7B%22name%22%…2UA-10846738-1%22%2C%22travis%22%3Atrue%7D&callback=callback”`
