### ISSUE TITLE
KeyError for missing field of type datetime when loaded from json

### ISSUE THREAD

**Issue by newtechfellas** [namlook/mongokit#197]
While creating a Document instance using json string, if the document property is of type datetime and JSON does not have that key, we see KeyError.
Error is raised from line 585 in document.py.
<pre>
<code>
elif struct[key] is datetime.datetime and doc[key] is not None:
</code>
</pre>

There is no check if the key exists in the doc. This causes it to throw KeyError

**Comment by eneepo** [comment]
Thanks for the report, this bug is fixed.
