### ISSUE TITLE
Python 3 

### ISSUE THREAD

**Issue by eneepo** [namlook/mongokit#226]
Once more I've merged the master into py3 branch and fixed the issues except those three that were left behind from last merge and I mentioned in pull request #151 .

These three test are introduced in this commit https://github.com/namlook/mongokit/commit/e8b7cb8bc4048b5c13e56e1e3737700cfaadc15c which is adding support for binary types. I'm not very familiar with the issue so I've be really grateful if anyone could fix them or at least helps me understand what is going on so that I can fix them(I'd be more grateful if someone could do both).

Other than that I think py3 is ready, please review and comment so that after updating the documentation we can merge it into master.

**Comment by u1735067** [comment]
I think this can be reopened, I just tried to use it with python3.4 and mongokit head version and it fails.

```
  File "/srv/emma/pymodules/mongokit/mongokit/schema_document.py", line 665
    except Exception, e:
                    ^
SyntaxError: invalid syntax
```

```
  File "/srv/emma/pymodules/mongokit_perso/mongokit/schema_document.py", line 338, in SchemaDocument
    long,
NameError: name 'long' is not defined
```
